on:
  push:
    branches:
      - main
  pull_request:

name: tests
env:
  # This is required to enable the web_sys clipboard API which egui_web uses
  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
  RUSTFLAGS: --cfg=web_sys_unstable_apis

#       - name: install tools
#         run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libpango1.0-dev libcairo2-dev libglib2.0-dev libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
        
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features cv/serde-serialize